channels:
- conda-forge
dependencies:
- python=3.8.2
- pip
- pip:
  - mlflow
  - torchvision>=0.9.1
  - cloudpickle==1.6.0
  - pytorch_lightning==1.7.6
  - ax-platform
  - prettytable
  - torch>=1.9.0
  - protobuf<4.0.0
  # gyptorch 1.9.0 is incompatible with the versions of botorch
  # required by many versions of pytorch
  - gpytorch!=1.9.0
  # Pinning pandas version less than 1.4.4 due to https://github.com/facebook/Ax/issues/1153
  - pandas<=1.4.4
